# Generated by Django 5.1.7 on 2025-03-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Permissao', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=94)),
                ('descricao', models.TextField()),
                ('Permissao_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Permissao.permissao')),
            ],
        ),
    ]
