# Generated by Django 5.2 on 2025-04-27 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='dataCriacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
