# Generated by Django 5.2 on 2025-04-12 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 13, 52, 42, 137495, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
