# Generated by Django 5.2 on 2025-04-12 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_chat_datacriacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='dataCriacao',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='dataCriacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
