# Generated by Django 5.2 on 2025-04-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_remove_chat_datacriacao_mensagem_datacriacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='dataCriacao',
            field=models.DateTimeField(),
        ),
    ]
