# Generated by Django 5.2 on 2025-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_alter_mensagem_datacriacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='dataCriacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
