# Generated by Django 5.1.7 on 2025-04-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permissao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermissaoUsuario',
        ),
    ]
