# Generated by Django 5.1.7 on 2025-04-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permissao', '0002_delete_permissaousuario'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='permissoes',
            field=models.ManyToManyField(to='Permissao.permissao'),
        ),
    ]
