# Generated by Django 5.1.7 on 2025-03-27 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.CharField(max_length=255)),
                ('vectorizer_path', models.CharField(max_length=255)),
                ('examples_count', models.IntegerField()),
                ('performance_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Agente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agente.agente')),
            ],
        ),
    ]
